# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

#ignore all warnings
inhibit_all_warnings!

target 'BAT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire'
  pod 'Firebase'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Auth', '~> 8.0'
  pod 'DCAnimationKit'
  
  # Pods for BAT

end
